#!/usr/bin/env python3
"""
Daily Summary Generator — Zero Human Corp
Generates end-of-day summaries and optionally emails them.
Runs via Ops agent heartbeat or cron.
"""

import json
import os
import smtplib
from datetime import datetime, timezone, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

MEMORY_DIR = Path("./memory")
REPORTS_DIR = Path("./economy/reports")
BOARD_FILE = Path("./symphony/board.json")
SUMMARIES_DIR = Path("./symphony/summaries")


def generate_daily_summary():
    """Generate a comprehensive daily summary."""
    SUMMARIES_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")

    # Load current state
    company_state = ""
    state_file = MEMORY_DIR / "company-state.md"
    if state_file.exists():
        company_state = state_file.read_text()

    # Load revenue log
    revenue_log = ""
    rev_file = MEMORY_DIR / "revenue-log.md"
    if rev_file.exists():
        revenue_log = rev_file.read_text()

    # Load decisions
    decisions = ""
    dec_file = MEMORY_DIR / "decisions.md"
    if dec_file.exists():
        decisions = dec_file.read_text()

    # Load task board
    board_summary = "No tasks yet"
    if BOARD_FILE.exists():
        with open(BOARD_FILE) as f:
            board = json.load(f)
        tasks = board.get("tasks", [])
        done_today = [t for t in tasks if t.get("status") == "DONE"]
        in_progress = [t for t in tasks if t.get("status") == "IN_PROGRESS"]
        in_review = [t for t in tasks if t.get("status") == "IN_REVIEW"]
        board_summary = f"""Tasks completed today: {len(done_today)}
Tasks in progress: {len(in_progress)}
Tasks in review: {len(in_review)}
Total tasks: {len(tasks)}"""

    # Parse today's revenue and costs
    total_revenue = 0.0
    total_costs = 0.0
    revenue_items = []
    cost_items = []

    for line in revenue_log.split("\n"):
        line = line.strip()
        if line.startswith("- REVENUE:") and today in line:
            try:
                amount = float(line.split("$")[1].split("|")[0].strip())
                total_revenue += amount
                revenue_items.append(line)
            except (IndexError, ValueError):
                pass
        elif line.startswith("- COST:") and today in line:
            try:
                amount = float(line.split("$")[1].split("|")[0].strip())
                total_costs += amount
                cost_items.append(line)
            except (IndexError, ValueError):
                pass

    # Load learnings
    learnings = ""
    learn_file = MEMORY_DIR / "learnings.md"
    if learn_file.exists():
        learnings = learn_file.read_text()

    # Build summary
    summary = f"""# Daily Summary — {today}
Generated at {now.strftime('%H:%M UTC')}

## Financial Overview
| Metric | Value |
|--------|-------|
| Revenue Today | ${total_revenue:.2f} |
| Costs Today | ${total_costs:.2f} |
| Net P&L Today | ${total_revenue - total_costs:.2f} |

## Task Board
{board_summary}

## Revenue Breakdown
{"No revenue today yet." if not revenue_items else chr(10).join(revenue_items)}

## Cost Breakdown
{"No costs today." if not cost_items else chr(10).join(cost_items)}

## Key Decisions Made Today
{decisions[-500:] if decisions else "No decisions logged yet."}

## What Was Learned
{learnings[-300:] if learnings else "No learnings logged yet."}

## Current Company State
{company_state[-500:] if company_state else "Not initialized."}

---

## Human Intervention Needed?
Check below for any items that require your attention:
- [ ] API keys or credentials needed
- [ ] Budget approval for spend > $10
- [ ] Strategic pivot approval
- [ ] Account creation on external services
- [ ] Any blocked tasks

*This summary was auto-generated by Sentinel (Ops Agent).*
"""

    # Save to file
    summary_file = SUMMARIES_DIR / f"summary-{today}.md"
    summary_file.write_text(summary)
    print(f"Daily summary saved to {summary_file}")

    return summary, summary_file


def send_email_summary(summary, recipient=None):
    """Send daily summary via email (optional)."""
    recipient = recipient or os.getenv("SUMMARY_EMAIL")
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")

    if not all([recipient, smtp_user, smtp_pass]):
        print("Email not configured. Summary saved to file only.")
        print("Set SUMMARY_EMAIL, SMTP_USER, SMTP_PASS in .env to enable.")
        return False

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Zero Human Corp — Daily Summary ({today})"
    msg["From"] = smtp_user
    msg["To"] = recipient

    # Plain text version
    msg.attach(MIMEText(summary, "plain"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        print(f"Summary emailed to {recipient}")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False


if __name__ == "__main__":
    summary, path = generate_daily_summary()
    send_email_summary(summary)
    print(f"\nSummary preview:\n{summary[:500]}...")
